<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CollectionKitSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('collection_kits')->insert([
            [
                'pcode' => 'CK-001',
                'name' => 'Needle',
                'color' => null,
                'charge' => 25.00,
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'pcode' => 'CK-002',
                'name' => 'Red',
                'color' => 'Red',
                'charge' => 15.00,
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'pcode' => 'CK-003',
                'name' => 'LAVENDER',
                'color' => 'Lavender',
                'charge' => 18.00,
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'pcode' => 'CK-004',
                'name' => 'Light Blue',
                'color' => 'Light Blue',
                'charge' => 22.00,
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'pcode' => 'CK-005',
                'name' => 'Gray',
                'color' => 'Gray',
                'charge' => 20.00,
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'pcode' => 'CK-006',
                'name' => 'Green',
                'color' => 'Green',
                'charge' => 19.00,
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'pcode' => 'CK-007',
                'name' => 'Yellow',
                'color' => 'Yellow',
                'charge' => 17.00,
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'pcode' => 'CK-008',
                'name' => 'Purple',
                'color' => 'Purple',
                'charge' => 21.00,
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'pcode' => 'CK-009',
                'name' => 'Orange',
                'color' => 'Orange',
                'charge' => 16.00,
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'pcode' => 'CK-010',
                'name' => 'Pink',
                'color' => 'Pink',
                'charge' => 14.00,
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'pcode' => 'CK-011',
                'name' => 'Brown',
                'color' => 'Brown',
                'charge' => 23.00,
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'pcode' => 'CK-012',
                'name' => 'MS Needle 22g',
                'color' => null,
                'charge' => 30.00,
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'pcode' => 'CK-013',
                'name' => 'MS Needle 23g',
                'color' => null,
                'charge' => 28.00,
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'pcode' => 'CK-014',
                'name' => 'Universal Holder',
                'color' => null,
                'charge' => 45.00,
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'pcode' => 'CK-015',
                'name' => 'Tourniquet',
                'color' => null,
                'charge' => 35.00,
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'pcode' => 'CK-016',
                'name' => 'Alcohol Swab',
                'color' => null,
                'charge' => 5.00,
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'pcode' => 'CK-017',
                'name' => 'Specimen Container',
                'color' => null,
                'charge' => 7.00,
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'pcode' => 'CK-018',
                'name' => 'RED-IMMU',
                'color' => 'Red',
                'charge' => 16.00,
                'status' => 'active',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
